settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: gin-lab
    path: .
    commands:
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
      scripts:
        - type: after
          command: ./main
          output: true
      ignore:
        paths:
          - .git
          - .realize
          - vendor
