version: "3"

services:

  dev-go:
    image: wevsmy/golang:1.13-alpine3.10-realize-v2.1
    container_name: dev-go
    environment:
      - GO111MODULE=on
      - GOPROXY=goproxy.io
      - GIN_MODE=debug
    working_dir: /gin-lab
    command: realize start
    ports:
      - "8080:8080"
    volumes:
      - "../../:/gin-lab"
